services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: cache
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123